#!/usr/bin/env bash

set -eu

export GOPATH=$PWD
export PATH="$PATH:$GOPATH/bin"

go get github.com/onsi/ginkgo/ginkgo

ginkgo -p -r -race -keepGoing -randomizeSuites -skipPackage "$IGNORE_PACKAGES" src/code.cloudfoundry.org/windows2016fs
