---
platform: windows

inputs:
- name: bosh-windows-stemcell-builder-ci
- name: bsdtar

outputs:
- name: tar-output

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - bosh-windows-stemcell-builder-ci/ci/tasks/build-tar/run.ps1
