#!/usr/bin/env bash

set -eu

pushd buildpack >/dev/null
  export GOPATH=$PWD
  export GOBIN=$PWD/.bin
  (cd src/*/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)
  ./.bin/buildpack-packager --cached
  buildpackFile=$(ls $BUILDPACK_NAME*.zip)

  cf api $CF_API --skip-ssl-validation
  cf auth $CF_ADMIN_USER $CF_ADMIN_PASSWORD
  cf update-buildpack $BUILDPACK_NAME -p $buildpackFile
popd >/dev/null

