#!/usr/bin/env bash
set -euo pipefail

set +x
if [ -n "${SSH_TUNNEL_USER:-}" ]; then
  source ./ci/common-scripts/setup_bosh_proxy.sh
  setup_bosh_proxy "${SSH_TUNNEL_USER}" "${SSH_TUNNEL_IP}" "${SSH_TUNNEL_PRIVATE_KEY}"
fi
set -x

ROOT_DIR=$(pwd)

pushd windows-utilities-release/src/windows-utilities-tests
  echo "Write config.json"
  export CONFIG_JSON=config.json
  cat > "${CONFIG_JSON}" <<-END_OF_CONFIG
  {
    "bosh": {
      "ca_cert": "$(ruby -e "puts ENV['BOSH_CA_CERT'].split(\"\n\").join('\n')")",
      "client": "${BOSH_CLIENT}",
      "client_secret": "${BOSH_CLIENT_SECRET}",
      "target": "${BOSH_ENVIRONMENT}",
      "ssh_tunnel_ip": "${SSH_TUNNEL_IP}",
      "gw_user": "${SSH_TUNNEL_USER}",
      "gw_private_key": "$(ruby -e "puts ENV['SSH_TUNNEL_PRIVATE_KEY'].split(\"\n\").join('\n')")"
    },
    "stemcell_path": "${ROOT_DIR}/${STEMCELL_PATH}",
    "windows_utilities_path": "${ROOT_DIR}/windows-utilities-release",
    "stemcell_os": "${STEMCELL_OS}",
    "az": "${AZ}",
    "vm_type": "${VM_TYPE}",
    "vm_extensions": "${VM_EXTENSIONS}",
    "network": "${NETWORK}",
    "skip_cleanup_on_rdp_fail": false
  }
END_OF_CONFIG

  go run github.com/onsi/ginkgo/ginkgo -v -nodes "${NODES}"
popd
