#!/usr/bin/env bash

set -ex

echo "Set GOPATH to $(pwd)"
export GOPATH=$(pwd)

pushd src/github.com/cloudfoundry-incubator/windows-utilities-tests
  set +x
  key_file=/tmp/bosh_ga.key
  prefix_pattern="-----BEGIN\|-----END\|RSA\|PRIVATE\|PUBLIC"
  echo $SSH_TUNNEL_PRIVATE_KEY \
    | sed -e "s/\($prefix_pattern\) /\1\t/g" \
    | sed -e "s/ /\n/g" \
    | sed -e "s/\($prefix_pattern\)\t/\1 /g" > $key_file
  chmod 600 $key_file
  export BOSH_GW_PRIVATE_KEY=$key_file
  set -x

  if [ "${IAAS}" == "aws" ]; then
      export BOSH_ALL_PROXY="ssh+socks5://${SSH_TUNNEL_USER}@${SSH_TUNNEL_IP}:22?private-key=${key_file}"
  fi

  echo "Write config.json"
  export CONFIG_JSON=config.json
  cat > $CONFIG_JSON <<- EOL
  {
    "bosh": {
      "ca_cert": "$(ruby -e "puts ENV['BOSH_CA_CERT'].split(\"\n\").join('\n')")",
      "client": "$BOSH_CLIENT",
      "client_secret": "$BOSH_CLIENT_SECRET",
      "target": "$BOSH_TARGET",
      "ssh_tunnel_ip": "$SSH_TUNNEL_IP",
      "gw_user": "$SSH_TUNNEL_USER",
      "gw_private_key": "$(ruby -e "puts ENV['SSH_TUNNEL_PRIVATE_KEY'].split(\"\n\").join('\n')")"
    },
    "stemcell_path": "$GOPATH/$STEMCELL_PATH",
    "windows_utilities_path": "../../../../windows-utilities-release",
    "stemcell_os": "$STEMCELL_OS",
    "az": "$AZ",
    "vm_type": "$VM_TYPE",
    "vm_extensions": "$VM_EXTENSIONS",
    "network": "$NETWORK"
  }
EOL

  echo "Build ginkgo"
  ginkgo_dir='./vendor/github.com/onsi/ginkgo/ginkgo'
  go build -o ginkgo $ginkgo_dir

  echo "Run ginkgo"
  ./ginkgo -v
popd
