---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: ci
  - name: windows-utilities-release
  - name: src/github.com/cloudfoundry/windows-utilities-tests
  - name: stemcell

run:
  path: ci/tasks/run-wuts/run

params:
  AZ:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_GW_USER:
  BOSH_ENVIRONMENT:
  IAAS:
  NETWORK:
  NODES: 4
  SSH_TUNNEL_IP:
  SSH_TUNNEL_PRIVATE_KEY:
  SSH_TUNNEL_USER:
  STEMCELL_OS:
  STEMCELL_PATH:
  VM_EXTENSIONS:
  VM_TYPE:
