#!/usr/bin/env bash

set -e

export CONFIG=$PWD/integration_config.json

cat > $CONFIG <<HERE
{
  "suite_name": "CF_SMOKE_TESTS",
  "apps_domain": "$DOMAIN",
  "api": "api.$DOMAIN",
  "use_existing_org": false,
  "use_existing_space": false,
  "org": "CF-SMOKE-ORG",
  "space": "CF-SMOKE-SPACE",
  "user": "admin",
  "password": "$ADMIN_PASSWORD",
  "enable_windows_tests": true,
  "skip_ssl_validation": true
}
HERE

mkdir -p $GOPATH/src/github.com/cloudfoundry
mv cf-smoke-tests $GOPATH/src/github.com/cloudfoundry/.

pushd $GOPATH/src/github.com/cloudfoundry/cf-smoke-tests
./bin/test
popd

rm $CONFIG

echo passed on `date`
