#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd lgpo-binary
  unzip LGPO.zip
popd

CONCOURSE_ROOT="$(pwd)"

"${CONCOURSE_ROOT}/ci/tasks/build-agent-zip/run.sh"

pushd stemcell-builder
  bundle install --without test

  rake package:psmodules
  rake build:azure

  mv bosh-windows-stemcell/* ../bosh-windows-stemcell

  mv hotfixes.log ../hotfix-log/
popd
