#!/usr/bin/env bash

set -ex

export BOSH_AGENT_DIR="$(pwd)/$BOSH_AGENT_DIR"
pushd "${BOSH_AGENT_DIR}"
  CURRENT_VERSION=$(cat .resource/version)
  mv bosh-agent*.exe bosh-agent.exe
popd

pushd stemcell-builder
  pushd src/github.com/cloudfoundry/bosh-agent
    git fetch
    git checkout "v$CURRENT_VERSION"
  popd
  bundle install --without test
  rake package:agent
  rake package:psmodules
  rake build:aws
popd

mv stemcell-builder/bosh-windows-stemcell/*.tgz bosh-windows-stemcell
mv stemcell-builder/bosh-windows-stemcell/*.sha sha

mv stemcell-builder/hotfixes.log hotfix-log/
