---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: heavy_stemcell_dir

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/pm-acceptance-upload-azure-stemcell/run

params:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  SSH_TUNNEL_IP:
  SSH_TUNNEL_PRIVATE_KEY:
  SSH_TUNNEL_USER:
