#!/bin/bash

set -e

export PATH=$(pwd)/bin:$PATH
export GOPATH=$(pwd)

pushd src/github.com/pivotal-cloudops/cf-sli
  go install
popd

cat > .config <<-EOF
{
  "api": "$CF_API",
  "user": "$CF_USERNAME",
  "pass": "$CF_PASSWORD",
  "org": "$CF_ORG",
  "space": "$CF_SPACE",
  "domain": "$CF_DOMAIN",
  "stack": "$CF_STACK",
  "skip_ssl_validation": true
}
EOF

# create org and space?

output=$(cf-sli -app-bits $APP_DIR -buildpack $CF_BUILDPACK)
stats=$(echo -e "$output" | tail -n 1)

app_route=$(echo $stats | jq .app_route)
app_start_time=$(echo $stats | jq .app_start_time_in_sec)
app_stop_time=$(echo $stats | jq .app_stop_time_in_sec)
app_start_status=$(echo $stats | jq .app_start_status)
app_stop_status=$(echo $stats | jq .app_stop_status)

currenttime=$(date +%s)

echo "Sending metrics to datadog..."

post_to_datadog () {
  local metric=$1
  local data_point_time=$2
  local data_point_value=$3
  local tag=$4

  curl -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\": \"$metric\",
            \"points\": [[$data_point_time, $data_point_value]],
            \"type\": \"gauge\",
            \"tags\": [\"$tag\"]
          }]
        }" \
  "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}&application_key=$DATADOG_APPLICATION_KEY"
}

post_to_datadog "cf_sli.${CF_STACK}.app_start_time_in_sec" $currenttime $app_start_time "$CF_TAG"
post_to_datadog "cf_sli.${CF_STACK}.app_stop_time_in_sec" $currenttime $app_stop_time "$CF_TAG"
post_to_datadog "cf_sli.${CF_STACK}.app_start_status" $currenttime $app_start_status "$CF_TAG"
post_to_datadog "cf_sli.${CF_STACK}.app_stop_status" $currenttime $app_stop_status "$CF_TAG"
