#!/usr/bin/env ruby

require_relative '../../../stemcell-builder/lib/exec_command'

Dir.chdir "stemcell-builder" do
  exec_command("bundle install --without test")
  exec_command("rake publish:staging:azure")
end
