#!/usr/bin/env bash

set -ex

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${AWS_ACCESS_KEY}"
  aws configure --profile creds_account set aws_secret_access_key "${AWS_SECRET_KEY}"
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  unset AWS_ACCESS_KEY
  unset AWS_SECRET_KEY
  export AWS_PROFILE=resource_account
else
  aws configure set aws_access_key_id "${AWS_ACCESS_KEY}"
  aws configure set aws_secret_access_key "${AWS_SECRET_KEY}"
fi

pushd bosh-agent-release
  BOSH_AGENT_VERSION=$(cat .resource/version)
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

cd stemcell-builder

bundle install

pushd src/github.com/cloudfoundry/bosh-agent
  git fetch
  git checkout "v${BOSH_AGENT_VERSION}"
popd

rake package:agent
rake package:psmodules
rake build:aws_ami

mv copied-regional-stemcells/*.tgz ../copied-regional-stemcells
