#!/usr/bin/env bash

set -ex

AWS_CREDS_FILE=~/.aws/credentials
mkdir -p ~/.aws

cat > ${AWS_CREDS_FILE} << EOF
[default]
aws_access_key_id = ${AWS_ACCESS_KEY}
aws_secret_access_key = ${AWS_SECRET_KEY}
EOF

pushd bosh-agent-release
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

cd stemcell-builder

bundle install
rake package:agent
rake package:psmodules
rake build:aws_ami

mv copied-regional-stemcells/*.tgz ../copied-regional-stemcells
