#!/usr/bin/env bash

set -ex

pushd stemcell-builder
bundle install --without test
rake package:agent
rake package:psmodules
rake build:gcp

popd
mv stemcell-builder/bosh-windows-stemcell/*.tgz bosh-windows-stemcell/

mv stemcell-builder/hotfixes.log hotfix-log/
