#!/usr/bin/env bash

set -ex

export BOSH_AGENT_DIR="$(pwd)/$BOSH_AGENT_DIR"

pushd "${BOSH_AGENT_DIR}"
  mv bosh-agent*.exe bosh-agent.exe
popd

pushd stemcell-builder
bundle install --without test
rake package:agent
rake package:psmodules
rake build:gcp

popd
mv stemcell-builder/bosh-windows-stemcell/*.tgz bosh-windows-stemcell/

mv stemcell-builder/hotfixes.log hotfix-log/
