---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/wait-for-azure-publisher-signoff/run

params:
  AZURE_PUBLISHER:
  AZURE_OFFER:
  PARTNER_PORTAL_TENANT_ID:
  PARTNER_PORTAL_CLIENT_ID:
  PARTNER_PORTAL_CLIENT_SECRET: