#!/usr/bin/env bash

set -eu

VERSION=$(cat version/version)
PREVIOUS_VERSION=$(cat windows2016fs-release/IMAGE_TAG)

if [[ "$VERSION" == "$PREVIOUS_VERSION" ]]; then
  echo "No blob to update"
else
  pushd windows2016fs-release
    printf $VERSION > IMAGE_TAG

    export GOPATH=$PWD
    mkdir -p blobs/windows2016fs
    go run src/oci-image/cmd/hydrate/main.go -image cloudfoundry/windows2016fs -outputDir blobs/windows2016fs -tag $VERSION

    bosh remove-blob "windows2016fs/windows2016fs-$PREVIOUS_VERSION.tgz"
    bosh add-blob "blobs/windows2016fs/windows2016fs-$VERSION.tgz" "windows2016fs/windows2016fs-$VERSION.tgz"
  popd
fi

rm "blobs/windows2016fs/windows2016fs-$VERSION.tgz"
cp -r ./windows2016fs-release/. windows2016fs-release-updated-blob/
