#!/usr/bin/env bash

set -eu

submodule_version=$(cat windows2016fs-release/src/code.cloudfoundry.org/windows2016fs/IMAGE_TAG)
blob_version=$(grep  windows2016fs windows2016fs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')

if [[ "$submodule_version" == "$blob_version" ]]; then
  echo "No blob to update"
else
  pushd windows2016fs-release
    export GOPATH=$PWD
    mkdir -p blobs/windows2016fs
    go run src/code.cloudfoundry.org/windows2016fs/cmd/hydrate/main.go -image cloudfoundry/windows2016fs -outputDir blobs/windows2016fs -tag $submodule_version

    bosh remove-blob "windows2016fs/windows2016fs-$blob_version.tgz"
    bosh add-blob "blobs/windows2016fs/windows2016fs-$submodule_version.tgz" "windows2016fs/windows2016fs-$submodule_version.tgz"

    rm "blobs/windows2016fs/windows2016fs-$submodule_version.tgz"
  popd
fi

cp -r ./windows2016fs-release/. windows2016fs-release-updated-blob/
