resource_types:
- name: ami-resource
  type: docker-image
  source:
    repository: pivotalgreenhouse/ami-resource
    tag: latest

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git
- name: stemcell-builder
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: bosh-agent-zip-version
  type: semver
  source:
    bucket: windows-bosh-integration
    key: versions/bosh-agent-version
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: windows-updates-list
  type: s3
  source:
    bucket: windows-updates-list
    regexp: update-list-(.*).csv
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-windows-shipit-version
  type: semver
  source:
    bucket: bosh-windows-client-consumable
    key: versions/consumable-version
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-windows-client-consumable
  type: s3
  source:
    bucket: bosh-windows-client-consumable
    regexp: bosh-windows-(.*).json
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: base-iso
  type: s3
  source:
    bucket: windows-bosh-private
    regexp: windows-(.*).iso
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-agent-zip
  type: s3
  source:
    bucket: windows-bosh-integration
    regexp: bosh-windows-integration-v(.*).zip
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-agent-deps-zip
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: agent-dependencies-v(.*).zip
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: ultradefrag-zip
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: ultradefrag-portable-(.*).bin.amd64.zip
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-vsphere-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/bosh-vsphere-stemcell-version
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-vsphere-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: ovftool-linux
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: ps-windows-update
  type: s3
  source:
    bucket: ps-windows-updates-module
    regexp: PSWindowsUpdate_v(.*).zip
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: windows-ami-eu-west-1
  type: ami-resource
  source:
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
    region: eu-west-1
    search_options:
      filters:
      - {name: "name", values: ["Windows_Server-2012-R2_RTM-English-64Bit-Base*"]}
      - {name: "state", values: ["available"]}
      owners:
      - amazon
- name: windows-ami-us-east-1
  type: ami-resource
  source:
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
    region: us-east-1
    search_options:
      filters:
      - {name: "name", values: ["Windows_Server-2012-R2_RTM-English-64Bit-Base*"]}
      - {name: "state", values: ["available"]}
      owners:
      - amazon
- name: windows-ami-us-west-2
  type: ami-resource
  source:
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
    region: us-west-2
    search_options:
      filters:
      - {name: "name", values: ["Windows_Server-2012-R2_RTM-English-64Bit-Base*"]}
      - {name: "state", values: ["available"]}
      owners:
      - amazon
- name: bosh-aws-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/bosh-aws-stemcell-version
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bosh-aws-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
- name: bwats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests.git

jobs:
- name: compile-and-push
  serial: true
  plan:
  - aggregate:
    - get: bosh-agent
    - get: bosh-agent-deps-zip
    - put: bosh-agent-zip-version
      params:
        bump: patch
  - task: compile-agent
    privileged: true
    file: bosh-agent/ci/tasks/compile-agent-windows.yml
  - put: bosh-agent-zip
    params:
      file: compiled-agent-zip/bosh-windows-integration-v*.zip

- name: create-vsphere-stemcell
  serial: true
  plan:
  - aggregate:
    - get: bosh-agent
      passed: [compile-and-push]
    - get: stemcell-builder
    - get: bosh-agent-deps-zip
    - get: bosh-agent-zip
      passed: [compile-and-push]
      trigger: true
    - get: ovftool-linux
    - get: ultradefrag-zip
    - get: base-iso
    - put: version
      resource: bosh-vsphere-stemcell-version
      params:
        bump: patch
    - get: ps-windows-update
    - get: bwats
    - get: ci
  - task: agent-sha
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: concourse/git-resource } }
      inputs:
      - name: bosh-agent
      outputs:
      - name: bosh-agent-sha
      run:
        path: bash
        args: ["-c","git --git-dir bosh-agent/.git rev-parse HEAD > bosh-agent-sha/sha"]
  - task: create-vsphere-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    tags: [vsphere-windows]
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      ISO_CHECKSUM_TYPE: "md5"
      ISO_CHECKSUM: "5b5e08c490ad16b59b1d9fab0def883a"
      MEMSIZE: "8192"
      NUMVCPUS: "6"
      REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
      REMOTE_PORT: "22"
      REMOTE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DIRECTORY: "packer-cache"
      REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
      REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
      ADMINISTRATOR_PASSWORD: {{WINDOWS_PASSWORD}}
      GUEST_NETWORK_ADDRESS: "10.85.58.10"
      GUEST_NETWORK_MASK: "255.255.255.0"
      GUEST_NETWORK_GATEWAY: "10.85.58.1"
    ensure:
      task: cleanup-vsphere
      file: ci/tasks/cleanup-vsphere.yml
      tags: [vsphere-windows]
      params:
        REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
        REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
        REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
        REMOTE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
  - task: test-stemcell
    file: bwats/concourse.yml
    tags: [vsphere-windows]
    params:
      BOSH_CLIENT_SECRET: {{STONETALON_BOSH_CLIENT_SECRET}}
      BOSH_CLIENT: {{STONETALON_BOSH_CLIENT_ID}}
      DIRECTOR_UUID: {{STONETALON_DIRECTOR_UUID}}
      DIRECTOR_IP: {{STONETALON_BOSH_DIRECTOR_IP}}
      STEMCELL_NAME: bosh-vsphere-esxi-windows-2012R2-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{STONETALON_BOSH_TARGET_CERT}}
  - put: bosh-vsphere-stemcell
    tags: [vsphere-windows]
    params:
      file: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
  - put: windows-updates-list
    params:
      file: updates-list/*.csv
- name: create-aws-stemcell
  plan:
  - aggregate:
    - get: ci
    - get: windows-ami-eu-west-1
    - get: windows-ami-us-east-1
    - get: windows-ami-us-west-2
    - get: stemcell-builder
    - get: bosh-agent
      passed: [compile-and-push]
    - put: version
      resource: bosh-aws-stemcell-version
      params:
        bump: patch
    - get: bosh-agent-zip
      passed: [compile-and-push]
      trigger: true
    - get: bosh-agent-deps-zip
    - get: bwats
  - task: agent-sha
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: concourse/git-resource } }
      inputs:
      - name: bosh-agent
      outputs:
      - name: bosh-agent-sha
      run:
        path: bash
        args: ["-c","git --git-dir bosh-agent/.git rev-parse HEAD > bosh-agent-sha/sha"]
  - task: collect-amis
    file: ci/tasks/collect-stemcell-region-amis.yml
    params:
      VPC_ID_EU_WEST_1: vpc-944df7f1
      SUBNET_ID_EU_WEST_1: subnet-0978c850
      VPC_ID_US_EAST_1: vpc-3e38385b
      SUBNET_ID_US_EAST_1: subnet-110fae67
      VPC_ID_US_WEST_2: vpc-fddc4a98
      SUBNET_ID_US_WEST_2: subnet-b46de0c3
  - task: create-stemcell
    file: stemcell-builder/tasks/create-aws-stemcell.yml
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      OS_VERSION: windows2012R2
      AWS_ACCESS_KEY: {{BOSH_CONCOURSE_ACCESS_KEY_ID}}
      AWS_SECRET_KEY: {{BOSH_CONCOURSE_SECRET_ACCESS_KEY}}
  - task: test-stemcell
    file: bwats/concourse.yml
    params:
      BOSH_PASSWORD: {{AWS_BOSH_PASSWORD}}
      BOSH_USER: {{AWS_BOSH_USER}}
      DIRECTOR_IP: 52.1.65.226:25555
      DIRECTOR_UUID: 5c99d18a-8615-4b1f-bb5a-268b798db37a
      STEMCELL_NAME: bosh-aws-xen-hvm-windows-stemcell-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
  - put: bosh-aws-stemcell
    params:
      file: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: shipit
  plan:
  - aggregate:
    - get: ci
    - get: bosh-agent
      passed: [create-vsphere-stemcell]
    - get: bosh-agent-zip
      passed: [create-vsphere-stemcell]
    - get: bosh-agent-deps-zip
      passed: [create-vsphere-stemcell]
    - get: windows-updates-list
      passed: [create-vsphere-stemcell]
    - get: bosh-windows-shipit-version
  - put: bosh-windows-shipit-version
    params:
      bump: patch
  - task: create-consumable
    file: ci/tasks/create-consumable.yml
  - put: bosh-windows-client-consumable
    params:
      file: bosh-windows-client-consumable/bosh-windows-*.json
