---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: bosh-windows-stemcell
  - name: version

outputs:
  - name: final-stemcell

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/set-stemcell-version/run
