---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: bosh-windows-stemcell-builder-ci

run: 
  path: bosh-windows-stemcell-builder-ci/ci/tasks/clean-up-pre-release-blobstore/run