#!/bin/bash

curl -f $CF_APP_URL
curlExitStatus=$?

set -e

appStillUp=0

if [[ $curlExitStatus == "0" ]]; then
  appStillUp=1
fi

curl -X POST -H "Content-type: application/json" \
  -d "{ \"series\" :
	 [{\"metric\": \"longrunning.apprunning\",
	  \"points\": [[$(date +%s), $appStillUp]],
	  \"type\": \"gauge\",
	  \"tags\": [\"$CF_TAG\"]
	}]
      }" \
"https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}&application_key=$DATADOG_APPLICATION_KEY"

exit $curlExitStatus
