---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/govc}}

inputs:
- name: bosh-windows-stemcell-builder-ci
- name: integration-vm-name
  optional: true

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/delete-integration-test-vm/run.sh

params:
  GOVC_INSECURE: 1
  VCENTER_ADMIN_CREDENTIAL_URL:
  CLONE_FOLDER:
