#!/usr/bin/env bash

set -eu

export GOPATH="$PWD/windows2016fs-release"
VERSION=$(cat version/version)
PREVIOUS_VERSION=$(cat windows2016fs-release/IMAGE_TAG)

go run windows2016fs-release/src/hydrate/cmd/hydrate/main.go \
  -image "cloudfoundry/windows2016fs"  \
  -outputDir /tmp \
  -tag $VERSION

pushd windows2016fs-release
  bosh remove-blob "windows2016fs/windows2016fs-$PREVIOUS_VERSION.tgz"
  bosh add-blob "/tmp/windows2016fs-$VERSION.tgz" "windows2016fs/windows2016fs-$VERSION.tgz"

  printf $VERSION > IMAGE_TAG

  # So copying the repo is faster
  rm -rf blobs/windows2016fs/*
popd

cp -r ./windows2016fs-release/. windows2016fs-release-updated/
