#!/usr/bin/env bash

set -ex

export BOSH_AGENT_DIR="$(pwd)/$BOSH_AGENT_DIR"

pushd "${BOSH_AGENT_DIR}"
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

cd stemcell-builder
bundle install
bundle exec rspec
