#!/usr/bin/env bash

set -ex

export BOSH_AGENT_DIR="$(pwd)/$BOSH_AGENT_DIR"

pushd "${BOSH_AGENT_DIR}"
#  CURRENT_VERSION=$(cat .resource/version)
  mv bosh-agent*.exe bosh-agent.exe
popd

cd stemcell-builder
bundle install
bundle exec rspec
