#!/bin/bash

set -e

BASE_URL_PATH="https://koaladefaultstore.blob.core.windows.net/stemcell/patchfile"
STRIP_PATCH_REGEX="s#\([0-9]*\.[0-9]*\)\.[0-9]*-build\.[0-9]*#\1#"

pushd patchfile
  SRC_PATCHFILE=$(ls patchfile-*)
  PATCHFILE=$(echo ${SRC_PATCHFILE} | sed -e "${STRIP_PATCH_REGEX}")
  mv ${SRC_PATCHFILE} ${PATCHFILE}
popd

pushd manifest
  SRC_MANIFEST=$(ls patchfile-*)
  MANIFEST=$(echo ${SRC_MANIFEST} | sed -e "${STRIP_PATCH_REGEX}")
  mv ${SRC_MANIFEST} ${MANIFEST}
  sed -e "s#patch_file: patchfile#patch_file: ${BASE_URL_PATH}/patchfile#" -i -- $MANIFEST
  sed -e "s#2012-vhd/##" -i -- $MANIFEST
  sed -e "${STRIP_PATCH_REGEX}" -i -- $MANIFEST
popd

echo "Copying ${SRC_PATCHFILE} to ${BASE_URL_PATH}/${PATCHFILE}"
azcopy --source ./patchfile --destination "${BASE_URL_PATH}" --include "patchfile-*" --dest-key "${STORAGE_ACCESS_KEY}" --quiet
echo "Copying ${SRC_MANIFEST} to ${BASE_URL_PATH}/${MANIFEST}"
azcopy --source ./manifest --destination "${BASE_URL_PATH}" --include "patchfile-*" --dest-key "${STORAGE_ACCESS_KEY}" --quiet
