---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: stembuild
- name: bosh-windows-stemcell-builder-ci
- name: govmomi

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/test-contract-stembuild-linux/run.sh

params:
  GOVC_INSECURE: 1
  VCENTER_ADMIN_CREDENTIAL_URL:
  VM_FOLDER:
  PACKAGE_TEST_VM_NAME:
  VCENTER_BASE_URL:
  VCENTER_USERNAME:
  VCENTER_PASSWORD:
  CONTRACT_TEST_VM_NAME:
  CONTRACT_TEST_VM_PASSWORD:
  CONTRACT_TEST_VM_USERNAME:
