#!/usr/bin/env bash

set -eu

echo "$SERVICE_ACCOUNT_KEY" > service-account.key.json

set -x

gcloud auth activate-service-account --key-file service-account.key.json
gsutil cp gs://$BUCKET/$FILE_NAME output
