#!/usr/bin/env bash

set -ex

pushd stemcell-builder
bundle install --without test
rake package:agent
rake package:psmodules
rake build:azure
mv bosh-windows-stemcell/* ../bosh-windows-stemcell

popd
mv stemcell-builder/hotfixes.log hotfix-log/
