#!/usr/bin/env bash

set -ex

sha=`cat stemcell-builder-released-sha/stemcell-*.json | jq -r '."stemcell-builder"'`
git clone https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder tmp

pushd tmp
  git checkout $sha
  git submodule update --init --recursive
popd

mv tmp/.[!.]* stemcell-builder/
mv tmp/* stemcell-builder/
