#!/usr/bin/env bash

set -eux

rsync -a concourse-windows-release/ concourse-windows-release-out

pushd concourse-windows-release-out
  rm config/blobs.yml
  touch config/blobs.yml
  cat > config/private.yml <<-EOF
---
blobstore:
  provider: s3
  options:
    credentials_source: env_or_profile
EOF

  version=$(cat ../concourse-github-release/version)
  bosh add-blob ../concourse-github-release/concourse_windows_amd64.exe concourse_windows/concourse_windows_amd64-$version.exe
  bosh upload-blobs

  git config user.email "pivotal-netgarden-eng@pivotal.io"
  git config user.name "CI (Automated)"
  git add -A .
  git commit -m "Bump concourse worker to $version"

  bosh create-release --final --name concourse-windows-worker --version $version --tarball ../concourse-windows-tarball/concourse-windows-worker-${version}.tgz
  git add -A .
  git commit -m "Create $version release"
popd

echo "* Bump Concourse worker to $version" > body/body.txt
