#!/usr/bin/env bash

set -eu

pre_version=$(cat version/version)
sha=$(cat sha/create-*-linux-amd64.sha256)

pushd windows2016fs-release
    echo -n "$pre_version" > VERSION
    echo -n "$sha" > CREATE_BIN_SHA_LINUX

    git config --global user.email "pivotal-netgarden-eng@pivotal.io"
    git config --global user.name "Greenhouse CI"
    git add VERSION CREATE_BIN_SHA_LINUX
    git commit -m "WIP - test"

  ./scripts/create-release --tarball ../release-tarball/release.tgz
popd
