#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'

stemcells = Dir.glob("*-{release-candidate,final}/*.tgz")
versions = stemcells.collect do |tarball|
  File.basename(tarball.scan(/\d+\.\d+\.\d+/)[0])
end

if versions.uniq.size > 1
  abort "Unable to find the same major and minor version for the inputs #{stemcells}"
end

puts "All stemcells have the same major and minor version."
