#!/usr/bin/env ruby

require 'open3'
require 'fileutils'

require_relative '../../../stemcell-builder/lib/exec_command'

Dir.chdir "stemcell-builder" do
  exec_command("bundle install")
  exec_command("rake package:psmodules")
  exec_command("rake build:vsphere_add_updates")
end
