#!/usr/bin/env bash

set -e

echo "Uploading $IAAS $OS stemcell to Pivnet"

case "$IAAS" in
    "aws")
      stemcellname='AWS light'
      ;;

    "gcp")
      stemcellname='GCP light'
      ;;

    "azure")
      stemcellname='Azure light'
      ;;

    "vsphere")
      stemcellname='vSphere'
      ;;

    *)
     echo "Invalid IAAS: $IAAS, supported IAASes are: awz, azure, gcp, vsphere"
     exit 1
esac


cat > pivnet-metadata/metadata <<EOF
---
release:
  version: "$(cat stemcell/version)"
  release_type: Beta Release
  eula_slug: "pivotal_beta_eula"
  availability: Admins Only
  user_group_ids: []
  eccn: ""
  license_exception: ""
product_files:
- file: final-$(ls stemcell/*.tgz)
  upload_as: "$stemcellname Stemcell for Windows $OS Server"
EOF

echo 'Release details:'
cat pivnet-metadata/metadata
