#!/usr/bin/env bash

set -e

go version

TIMESTAMP=$(date +%s)

export GOPATH="$PWD/windows2016fs-release"

go build -o "output/create-$TIMESTAMP-linux-amd64" create

sha=$(sha256sum "output/create-$TIMESTAMP-linux-amd64" | awk '{ print $1 }')
printf $sha > "output/create-$TIMESTAMP-linux-amd64.sha256"

GOOS=windows go build -o "output/create-$TIMESTAMP-windows-amd64.exe" create

sha=$(sha256sum "output/create-$TIMESTAMP-windows-amd64.exe" | awk '{ print $1 }')
printf $sha > "output/create-$TIMESTAMP-windows-amd64.exe.sha256"

printf $TIMESTAMP > "output/create-$TIMESTAMP-timestamp"
