#!/bin/bash

set -e

cf api "$CF_API" --skip-ssl-validation
cf login -u "$CF_USERNAME" -p "$CF_PASSWORD"  -o "system" --skip-ssl-validation

cf create-security-group credhub-internal <(echo '[{
  "destination": "10.0.16.0/24",
  "ports": "8844",
  "protocol": "tcp"
}]')

cf bind-staging-security-group credhub-internal
cf bind-running-security-group credhub-internal

cf set-running-environment-variable-group '{"CREDHUB_API": "https://credhub.service.cf.internal:8844"}'
