#!/usr/bin/env bash

set -eu

rm -rf garden-runc-release/src/code.cloudfoundry.org/garden-integration-tests
echo "Copying GATS fork...."
cp -r garden-integration-tests garden-runc-release/src/code.cloudfoundry.org/garden-integration-tests

echo "Copying into garden-runc-release-forks"
cp -r ./garden-runc-release/* ./garden-runc-release-forks
