#!/usr/bin/env bash

set -euo pipefail

#stemcell=`ls stembuild/stembuild*`
#stemcellname=stembuild4


release_version=$(cat pivnet-release/metadata.json | jq -r .Release.Version)
echo "ls ***"
ls pivnet-release

VERSION='stembuild-promote-test'
echo $VERSION > stembuild/version

FILE_GROUP_ID=$(cat pivnet-release/metadata.json |jq '.FileGroups[0].ID')
echo "File Group ID is: $FILE_GROUP_ID"

#mkdir pivnet-metadata/stembuild
#mv stembuild/stembuild* pivnet-metadata

pivnet login --api-token=$PIVNET_API_TOKEN --host=$PIVNET_ENDPOINT
# info:
pivnet file-group --product-slug=$PRODUCT_SLUG --file-group-id=$FILE_GROUP_ID


#mv pivnet-metadata/stembuild* pivnet-metadata/stembuild-test2
FILE_IDS=$(cat pivnet-release/metadata.json |jq '.ProductFiles[] | select( .File | contains("stembuild") ) | .ID')
#RELEASE_ID=$(cat pivnet-release/metadata.json |jq '.Release.ID')
for i in $FILE_IDS; do
  pivnet add-product-file --product-slug=$PRODUCT_SLUG --product-file-id=$i --file-group-id=$FILE_GROUP_ID
  pivnet remove-product-file --product-slug=$PRODUCT_SLUG --release-version=$VERSION --product-file-id=$i
done


cat pivnet-release/metadata.json
echo
