#!/usr/bin/env bash

set -e

function add-pivnet-productfile () {
  stemcell="$1"

  echo "Adding $stemcell to Pivnet metadata"

  cat >> metadata-with-folder <<EOF
  - file: pivnet-metadata/$stemcell
    upload_as: "$stemcell Stemcell for $OS_NAME"
EOF
}

function add-stembuild-id() {
  id="$1"

  echo "Adding stembuild by id: $id to Pivnet metadata"

  cat >> metadata-with-folder <<EOF
    - id: $id
EOF

}

stemcell=`ls stembuild/stembuild*`
stemcellname=stembuild4

cat > pivnet-metadata/metadata-with-folder <<EOF
---
release:
  version: "stembuild-promote-test"
  release_type: Beta Release
  eula_slug: "pivotal_beta_eula"
  availability: Selected User Groups Only
  user_group_ids:
    - 152
  eccn: ""
  license_exception: ""
EOF


release_version=$(cat pivnet-release/metadata.json | jq -r .Release.Version)
echo "ls ***"
ls pivnet-release

echo "stembuild-promote-test" > stembuild/version
#if [ "$(ls pivnet-release/stembuild*)" != "" ] && [[ $release_version == *"$(cat stembuild/version)"* ]]; then
#    mv pivnet-release/stembuild* pivnet-metadata
#fi
if [ "$(ls pivnet-release/*stemcell*)" != "" ] && [[ $release_version == *"$(cat stembuild/version)"* ]]; then
    mv pivnet-release/*stemcell* pivnet-metadata
fi

FOLDER_GROUP_ID=$(cat pivnet-release/metadata.json |jq '.FileGroups[0].ID')
echo "File Group ID is: $FOLDER_GROUP_ID"

pushd pivnet-metadata
cat >> metadata-with-folder <<EOF
product_files:
EOF
for s in $(ls *stemcell*)
  do
    add-pivnet-productfile "$s"
done

cat >> metadata-with-folder <<EOF
file_groups:
  - id: $FOLDER_GROUP_ID
    product_files:
EOF
popd

#for f in $(ls stembuild*)
#  do
#    FILE_ID=$(echo pivnet-release/metadata.json | jq .product_files\(?????\))
#done


#mkdir pivnet-metadata/stembuild
#mv stembuild/stembuild* pivnet-metadata

#mv pivnet-metadata/stembuild* pivnet-metadata/stembuild-test2
FILE_IDS=$(cat pivnet-release/metadata.json |jq '.ProductFiles[] | select( .File | contains("stembuild") ) | .ID')

pushd pivnet-metadata
for i in $FILE_IDS
  do
    add-stembuild-id "$i"
done
popd

echo 'Release details:'
cat pivnet-metadata/metadata-with-folder
echo

cat pivnet-release/metadata.json
echo
