#!/usr/bin/env bash

set -e

pre_version=$(cat version/version)

pushd windows2016fs-release
  if [[ -n "$DEV_ENV" ]]; then
      echo -n "$pre_version" > VERSION
      git add VERSION
      git commit -m "WIP - test"
  fi

  ./scripts/create-release
popd

if [[ -z "$DEV_ENV" ]]; then
  cp windows2016fs-release/bin/create "create-binary-linux/create-$pre_version-linux-amd64"
fi
