#!/usr/bin/env bash

set -e

timestamp=$(cat create-timestamp/create-*-timestamp)
sha=$(cat sha/create-*-linux-amd64.sha256)

pushd windows2016fs-release
  if [[ -z "$DEV_ENV" ]]; then
    echo -n "$timestamp" > VERSION
    echo -n "$sha" > CREATE_BIN_SHA_LINUX

    git config --global user.email "pivotal-netgarden-eng@pivotal.io"
    git config --global user.name "Greenhouse CI"
    git add VERSION CREATE_BIN_SHA_LINUX
    git commit -m "WIP - test"
  fi

  mkdir new-dir
  ./scripts/create-release --tarball ./new-dir/release.tgz
popd
