#!/usr/bin/env bash

set -e

function add-pivnet-productfile () {
  stemcell="$1"

  echo "Adding $stemcell to Pivnet metadata"
  case "$stemcell" in
      *"aws"*)
        stemcellname='AWS light'
        ;;

      *"google"*)
        stemcellname='GCP light'
        ;;

      *"azure"*)
        stemcellname='Azure light'
        ;;

      *"vsphere"*)
        stemcellname='vSphere'
        ;;
      "stembuild-linux-x86_64"*)
        stemcellname='Stembuild for Linux'
        ;;
      "stembuild-windows-x86_64"*)
        stemcellname='Stembuild for Windows'
        ;;
      *)
       echo "Invalid stemcell: $stemcell, supported IAASes are: aws, azure, google, vsphere"
       exit 1
  esac

  cat >> metadata <<EOF
  - file: pivnet-metadata/$stemcell
    upload_as: "$stemcellname Stemcell for $OS_NAME"
EOF
}

release_version=$( cat version/version | cut -d '.' -f1-2 )

cat > pivnet-metadata/metadata <<EOF
---
release:
  version: "${release_version}"
  release_type: Security Release
  eula_slug: "pivotal_software_eula"
  availability: Selected User Groups Only
  user_group_ids:
    - 164
  eccn: "5D002"
  license_exception: "ECCN"
product_files:
EOF

release_version=$(cat pivnet-release/metadata.json | jq .Release.Version)
if [ "$(ls pivnet-release/*.tgz)" != "" ] && [[ $release_version == *"$(cat stemcell/version)"* ]]; then
  mv pivnet-release/*.tgz pivnet-metadata
fi

mv file-to-upload/* pivnet-metadata

cd pivnet-metadata
for s in $(ls *.tgz)
  do
    add-pivnet-productfile "$s"
done

for s in $(ls stembuild-linux-x86_64*)
  do
    add-pivnet-productfile "$s"
done

for s in $(ls stembuild-windows-x86_64*)
  do
    add-pivnet-productfile "$s"
done
cd ..

echo 'Release details:'
cat pivnet-metadata/metadata

echo 'Stemcells:'
ls pivnet-metadata/*.tgz
