FROM microsoft/windowsservercore

RUN powershell.exe -Command \
  $ErrorActionPreference = 'Stop'; \
  \
  Add-WindowsFeature Web-Webserver, \
    Web-WebSockets, \
    Web-WHC, \
    Web-ASP, \
    Web-ASP-Net45

RUN cmd.exe /C net users /ADD vcap /passwordreq:no && runas /user:vcap whoami
RUN powershell.exe -Command Invoke-WebRequest -Uri https://s3.amazonaws.com/bosh-windows-dependencies/tar-1490035387.exe -UseBasicParsing -OutFile C:\\Windows\\tar.exe

