FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      ca-certificates \
      jq \
      wget

RUN wget -q https://github.com/pivotal-cf/pivnet-cli/releases/download/v4.1.1/pivnet-linux-amd64-4.1.1 -O pivnet \
    && echo '5462367e67836cda6ecf3fb87b72d22947dcb385aeb217bf896bcc05b99559eb  pivnet' \
      | sha256sum --check \
    && install pivnet /usr/local/bin/
