FROM ubuntu:16.04

RUN wget -q https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq && chmod +x /usr/local/bin/jq

RUN wget -q https://github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.57/pivnet-linux-amd64-0.0.57 -O /usr/local/bin/pivnet
RUN echo '4f7ba30c2e9125439b40b5623226878e9530c81987224817acd36ea227fdabe2  /usr/local/bin/pivnet' | sha256sum --check
RUN chmod 500 /usr/local/bin/pivnet

