---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: ci
- name: version

outputs:
- name: base-amis

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ROLE_ARN:
  BASE_AMI:
  BASE_AMI_NAME:
  PACKER_REGION:


run:
  path: ci/tasks/collect-base-amis/run
