---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: bosh-windows-stemcell-builder-ci

params:
  ACCOUNT_JSON:

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/cleanup-unpublished-gcp-images/run
