#!/usr/bin/env bash

set -ex

echo "Set GOPATH to $(pwd)"
export GOPATH=$(pwd)

echo "Make the bosh release for windows utilities"
pushd windows-utilities-release
  bosh cr --tarball=release.tgz
popd



pushd src/github.com/cloudfoundry-incubator/windows-utilities-tests
  echo "Write config.json"
  export CONFIG_JSON=config.json
  cat > $CONFIG_JSON <<- EOL
  {
    "bosh": {
    "ca_cert": "$(ruby -e "puts ENV['BOSH_CA_CERT'].split(\"\n\").join('\n')")",
      "client": "$BOSH_CLIENT",
      "client_secret": "$BOSH_CLIENT_SECRET",
      "target": "$BOSH_TARGET",
      "gw_user": "$BOSH_GW_USER",
      "gw_private_key": "$(ruby -e "puts ENV['BOSH_GW_PRIVATE_KEY'].split(\"\n\").join('\n')")"
    },
    "stemcell_path": "$GOPATH/$STEMCELL_PATH",
    "windows_utilities_path": "$GOPATH/windows-utilities-release/release.tgz",
    "stemcell_os": "$STEMCELL_OS",
    "az": "$AZ",
    "vm_type": "$VM_TYPE",
    "vm_extensions": "$VM_EXTENSIONS",
    "network": "$NETWORK"
  }
EOL

  echo "Build ginkgo"
  ginkgo_dir='./vendor/github.com/onsi/ginkgo/ginkgo'
  go build -o ginkgo $ginkgo_dir

  echo "Run ginkgo"
  ./ginkgo -v
popd

