#!/usr/bin/env ruby

require 'tracker_api'

token = ARGV[0]
project_id = ARGV[1].to_i
image_version = ARGV[2]

client = TrackerApi::Client.new(token: token)
project = client.project(project_id)

name = "New version of cloudfoundry/windows2016fs #{image_version}"
description = 'A new version of cloudfoundry/windows2016fs is available. Once all the pipelines are green, release new versions of the BOSH releases that consume it'
tasks = [{description: 'release cloudfoundry-incubator/windows2016fs-release'},
         {description: 'release cloudfoundry-incubator/windows2016fs-online-release'}]
labels = ['windows2016fs-release', 'windows2016fs-online-release']

project.create_story(
  name: name,
  description: description,
  tasks: tasks,
  estimate: 1,
  labels: labels
)
