---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stembuild-stemcell-tested
  - name: aws-tested
  - name: aws-govcloud-tested
  - name: gcp-tested
  - name: azure-tested
  - name: stembuild-untested-linux
  - name: stembuild-untested-windows

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/match-stemcell-versions/run
