#!/usr/bin/env ruby
require 'json'

dirs = %w(stemcell-builder
          stemcell-builder/src/github.com/cloudfoundry/bosh-agent
          stemcell-builder/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests)

stemcell = Dir.glob("final-stemcell/*.tgz")[0]
final_version = stemcell.match(/\d+\.\d+/)[0]

if stemcell.match('windows2012R2')
  filename = "stemcell-#{final_version}.json"
elsif stemcell.match('windows2016')
  # Use 2016 as a prefix so it doesn't match the 2012 regex
  filename = "2016-stemcell-#{final_version}.json"
else
  throw "invalid stemcell filename: #{stemcell}"
end

shas = dirs.inject({}) do |acc, dir|
  acc[dir.split('/').last] = `cd #{dir}; git rev-parse HEAD`.chomp
  acc
end

File.write(
  File.join('stemcell-info', filename),
  JSON.dump(shas)
)
