#!/usr/bin/env ruby

require 'fileutils'
require 'erb'

@version = `cat version/version`

template_name = ENV['DEST_NAME']
renderer = ERB.new(template_name)
final_name = renderer.result()
FileUtils.cp("source/#{ENV['SOURCE_NAME']}","dest/#{final_name}")
