---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
- name: bosh-psmodules-repo
- name: ci
- name: stemcell-builder

outputs:
- name: bosh-psmodules

run:
  path: ci/tasks/build-psmodules-zip/run.sh

params:
  BOSH_PSMODULES_DIR: bosh-psmodules-repo
  ZIP_OUTPUT_DIR: bosh-psmodules
