# ~/workspace/greenhouse-private/dotfiles-scripts/fly-docker-images
resources:
# dockerfiles

- name: ci-pivnet-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.pivnet ]

- name: ci-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.ci ]

- name: govc-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.govc ]

- name: ci-azcopy-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.azcopy ]

# docker build resources

- name: pivnet-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/pivnet
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

- name: ci-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

- name: govc-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/govc
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

- name: ci-azcopy-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci-azcopy
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASSWORD}}

# dependency resources

- name: go-dep
  type: github-release
  source:
    access_token: ((github_read_only_token))
    owner: golang
    repository: dep
jobs:
- name: build-and-push-pivnet
  plan:
  - get: ci-pivnet-dockerfile
    trigger: true
  - put: pivnet-image
    params:
      build: ci-pivnet-dockerfile/docker
      dockerfile: ci-pivnet-dockerfile/docker/Dockerfile.pivnet
      tag_as_latest: true

- name: build-and-push-ci
  plan:
  - get: ci-dockerfile
    trigger: true
  - get: go-dep
  - task: copy-dep
    config:
      inputs:
        - name: go-dep
        - name: ci-dockerfile
      outputs:
        - name: docker-build-dir
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}
      run:
        path: cp
        args:
          - -R
          - go-dep
          - ci-dockerfile/docker
          - docker-build-dir
  - put: ci-image
    params:
      build: docker-build-dir
      dockerfile: docker-build-dir/docker/Dockerfile.ci
      tag_as_latest: true

- name: build-and-push-govc
  plan:
    - get: govc-dockerfile
      trigger: true
    - put: govc-image
      params:
        build: govc-dockerfile/docker
        dockerfile: govc-dockerfile/docker/Dockerfile.govc
        tag_as_latest: true

- name: build-and-push-ci-azcopy
  plan:
    - get: ci-azcopy-dockerfile
      trigger: true
    - put: ci-azcopy-image
      params:
        build: ci-azcopy-dockerfile/docker
        dockerfile: ci-azcopy-dockerfile/docker/Dockerfile.azcopy
        tag_as_latest: true
