resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
groups:
- name: main
  jobs:
  - tartar-deploy-cf
  - bump-garden-windows-blob
  - sync-garden-windows-release-submodules
  - shipit
  - merge-master-into-develop
- name: bumps
  jobs:
  - patch-bump
  - minor-bump
  - major-bump
resources:
- name: garden-runc-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-runc-release.git
- name: garden-windows-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/garden-windows-release.git
    private_key: {{CLOUDFOUNDRY_GARDEN-WINDOWS-RELEASE_DEPLOY_KEY}}
- name: garden-windows-bosh-release-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/garden-windows-bosh-release.git
    private_key: {{CLOUDFOUNDRY-INCUBATOR_GARDEN-WINDOWS-BOSH-RELEASE_PRIVATE_KEY}}
- name: garden-windows-bosh-release-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/garden-windows-bosh-release.git
    private_key: {{CLOUDFOUNDRY-INCUBATOR_GARDEN-WINDOWS-BOSH-RELEASE_PRIVATE_KEY}}
- name: garden-windows-bosh-release-develop-mergedback
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry-incubator/garden-windows-bosh-release.git
    private_key: {{CLOUDFOUNDRY-INCUBATOR_GARDEN-WINDOWS-BOSH-RELEASE_PRIVATE_KEY}}
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: garden-windows-private
  type: git
  source:
    branch: master
    private_key: {{GARDEN_WINDOWS_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/garden-windows-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: tartar-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: {{TARTAR_BOSH_CLIENT}}
    client_secret: {{TARTAR_BOSH_CLIENT_SECRET}}
    ca_cert: {{TARTAR_BOSH_CA_CERT}}
    target: {{TARTAR_BOSH_ENVIRONMENT}}
    vars_store:
      provider: gcs
      config:
        bucket: cf-greenhouse-tartar
        file_name: cf/creds.yml
        json_key: {{TARTAR_SERVICE_ACCOUNT_JSON}}
- name: tartar-lock-pool
  type: pool
  source:
    branch: master
    pool: tartar
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: garden-windows-bosh-artifacts
  type: s3
  source:
    bucket: build-garden-windows-bosh-artifacts
    regexp: bosh-executables-(\d+\.\d+).*\.zip
- name: garden-windows-bosh-release-bucket-dev
  type: s3
  source:
    bucket: garden-windows-dev-bosh-release
    regexp: garden-windows-(.*).tgz
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
- name: garden-windows-bosh-release-bucket-final
  type: s3
  source:
    bucket: garden-windows-bosh-release
    regexp: garden-windows-(.*).tgz
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
- name: version
  type: semver
  source:
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
    bucket: garden-windows-bosh-release
    initial_version: 0.0.0
    key: version
    region_name: us-east-1
- name: wats-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats
- name: wats-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/wats
- name: wats-mergedback
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/wats
    private_key: {{CLOUDFOUNDRY_WATS_DEPLOY_KEY}}
- name: garden-windows-bosh-github-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: garden-windows-bosh-release
    drafts: true
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}
- name: cf-deployment
  type: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: all-bosh-windows
    regexp: 2012R2/tested/gcp/light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
jobs:
- name: sync-garden-windows-release-submodules
  serial: true
  plan:
  - aggregate:
    - get: upstream-release
      resource: garden-runc-release
      trigger: true
    - get: downstream-release
      resource: garden-windows-release
    - get: ci
  - task: sync-submodules
    file: ci/sync-submodules/task.yml
    params:
      SUBMODULES: "src/code.cloudfoundry.org/garden,src/github.com/bmizerany/pat,src/github.com/cloudfoundry/dropsonde,src/github.com/cloudfoundry/gosteno,src/github.com/cloudfoundry/sonde-go,src/github.com/gogo/protobuf,src/github.com/golang/protobuf,src/github.com/gorilla/context,src/github.com/gorilla/mux,src/github.com/nu7hatch/gouuid,src/github.com/onsi/ginkgo,src/github.com/onsi/gomega,src/github.com/pivotal-golang/localip,src/github.com/tedsuo/ifrit,src/golang.org/x/net,src/gopkg.in/yaml.v2"
  - put: garden-windows-release
    params:
      repository: bumped-downstream-release

- name: tartar-deploy-cf
  serial: true
  plan:
  - put: tartar-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
        trigger: true
      - get: garden-windows-bosh-release-develop
        trigger: true
      - get: gcp-windows-stemcell
        trigger: true
      - get: wats-develop
        trigger: true
      - get: wats-master
      - get: version
        params: {pre: rc}
      - get: ci
      - get: garden-windows-private
    - put: version
      params:
        file: version/number
    - task: create-release
      file: ci/bosh-cr/task.yml
      input_mapping: { release: garden-windows-bosh-release-develop }
    - task: get-linux-stemcell
      file: ci/get-gcp-linux-stemcell/task.yml
      output_mapping: { stemcell: gcp-linux-stemcell }
    - task: get-cf-vars
      file: ci/get-gcs-file/task.yml
      output_mapping: { output: cf-vars }
      params:
        BUCKET: cf-greenhouse-tartar
        FILE_NAME: cf/vars.yml
        SERVICE_ACCOUNT_KEY: {{TARTAR_SERVICE_ACCOUNT_JSON}}
    - put: tartar-cf-deployment
      params:
        manifest: cf-deployment/cf-deployment.yml
        stemcells:
        - gcp-linux-stemcell/*.tgz
        - gcp-windows-stemcell/*.tgz
        releases:
        - release-tarball/*.tgz
        ops_files:
        - cf-deployment/operations/windows-cell.yml
        - cf-deployment/operations/scale-to-one-az.yml
        - cf-deployment/operations/workaround/use-3-azs-for-router.yml
        - cf-deployment/operations/use-latest-windows-stemcell.yml
        - cf-deployment/operations/experimental/enable-prefer-declarative-healthchecks-windows.yml
        - cf-deployment/operations/experimental/use-bosh-dns.yml
        - cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml
        - cf-deployment/operations/experimental/skip-consul-cell-registrations.yml
        - cf-deployment/operations/experimental/skip-consul-locks.yml
        - cf-deployment/operations/experimental/enable-instance-identity-credentials.yml
        - cf-deployment/operations/experimental/enable-instance-identity-credentials-windows.yml
        - cf-deployment/operations/experimental/secure-service-credentials.yml
        - cf-deployment/operations/experimental/secure-service-credentials-windows-cell.yml
        - cf-deployment/operations/experimental/disable-consul.yml
        - cf-deployment/operations/experimental/disable-consul-windows.yml
        - garden-windows-private/operations-common/latest-garden-windows.yml
        - garden-windows-private/operations-common/scale-down-credhub.yml
        vars_files:
        - cf-vars/vars.yml
        cleanup: true
      get_params:
        skip_export: true
    - task: clean-up
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{TARTAR_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{TARTAR_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{TARTAR_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{TARTAR_BOSH_CA_CERT}}
    - task: enable-credhub
      file: ci/enable-credhub/task.yml
      params:
        CF_API: api.tartar.cf-app.com
        CF_USERNAME: admin
        CF_PASSWORD: {{TARTAR_ADMIN_PASSWORD}}
    - task: wats
      file: ci/run-wats/task.yml
      input_mapping: { wats: wats-develop }
      params:
        ADMIN_PASSWORD: {{TARTAR_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.tartar.cf-app.com
        APPS_DOMAIN: tartar.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
        CONSUL_MUTUAL_TLS: false
        TEST_TASK: true
        CREDHUB_MODE: assisted
      on_success:
        task: delete-deployment
        file: ci/bosh-deld/task.yml
        params:
          BOSH_DEPLOYMENT: cf
          BOSH_ENVIRONMENT: {{TARTAR_BOSH_ENVIRONMENT}}
          BOSH_CLIENT: {{TARTAR_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{TARTAR_BOSH_CLIENT_SECRET}}
          BOSH_CA_CERT: {{TARTAR_BOSH_CA_CERT}}
    - task: rename
      file: ci/rename/task.yml
      input_mapping: { source: release-tarball }
      output_mapping: { dest: garden-windows-output }
      params:
        SOURCE_NAME: "release.tgz"
        DEST_NAME: "garden-windows-<%= @version %>.tgz"
    - put: garden-windows-bosh-release-bucket-dev
      params:
        file: garden-windows-output/garden-windows-*.tgz
    - task: merge-develop-to-master
      input_mapping: { from-repo: wats-develop, to-repo: wats-master }
      file: ci/merge-repo/task.yml
      params:
        FROM_BRANCH: develop
    - put: wats-mergedback
      params: { repository: merged-repo/to-repo }
    ensure:
      put: tartar-lock-pool
      params:
        release: tartar-lock-pool

- name: shipit
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: greenhouse-private
    - get: version
      params: {bump: final}
    - get: release-develop
      resource: garden-windows-bosh-release-develop
      passed: [tartar-deploy-cf]
    - get: release-master
      resource: garden-windows-bosh-release-master
    - get: bucket-develop
      resource: garden-windows-bosh-release-bucket-dev
      passed: [tartar-deploy-cf]
  - put: version
    params: {file: version/number}
  - task: finalize-release
    file: ci/finalize-release/task.yml
    input_mapping: { release: release-develop }
    params:
      RELEASE_NAME: garden-windows
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: garden-windows-bosh-release-bucket-final
    params:
      file: finalized-release/garden-windows-*.tgz
  - put: garden-windows-bosh-release-master
    params:
      repository: finalized-release/release
      tag: version/number
      tag_prefix: v
  - task: generate-release
    input_mapping: { release: release-master }
    file: ci/generate-github-release/task.yml
  - put: garden-windows-bosh-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
      globs:
      - finalized-release/garden-windows-*.tgz
- name: merge-master-into-develop
  plan:
    - aggregate:
      - get: ci
      - get: from-repo
        resource: garden-windows-bosh-release-master
        trigger: true
        passed: [shipit]
        params:
          submodules: none
      - get: to-repo
        resource: garden-windows-bosh-release-develop
        params:
          submodules: none
    - task: merge-master-into-develop
      file: ci/merge-repo/task.yml
      params:
        FROM_BRANCH: master
    - put: garden-windows-bosh-release-develop-mergedback
      params:
        repository: merged-repo/to-repo
- name: patch-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: bump-garden-windows-blob
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: release
      resource: garden-windows-bosh-release-develop
    - get: garden-windows-bosh-artifacts
      trigger: true
  - task: update-blobs
    file: ci/update-garden-windows-blobs/task.yml
    params:
      ACCESS_KEY_ID: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
      SECRET_ACCESS_KEY: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}
  - put: garden-windows-bosh-release-develop
    params:
      repository: release-output
      rebase: true
