resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: hwc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/hwc.git
- name: hwc-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/hwc.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_HWC_DEPLOY_KEY}}
- name: hwc-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: hwc
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}
- name: hwc-version
  type: semver
  source:
    bucket: hwc-release
    key: versions/hwc-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: "1.0.0"
jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: hwc-develop
      trigger: true
    - get: hwc-master
  - task: test-hwc
    input_mapping: { hwc: hwc-develop }
    file: ci/test-hwc/task.yml
  - task: merge-develop-to-master
    input_mapping: { from-repo: hwc-develop, to-repo: hwc-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: hwc-master
    params: { repository: merged-repo/to-repo }

- name: build-and-release
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: hwc
      resource: hwc-master
      passed: [test]
    - get: hwc-version
  - task: build-hwc
    file: ci/build-hwc/task.yml
  - put: hwc-version
    params: {bump: major}
  - put: hwc-release
    params:
      name: hwc-version/number
      tag: hwc-version/number
      globs:
      - hwc-rel/hwc.exe
