resources:
- name: s3-bucket
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bsdtar
  type: git
  source:
    branch: master
    uri: https://github.com/greenhouse-org/bsdtar.git
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent
- name: bosh-agent-fork
  type: git
  source:
    branch: master
    uri: git@github.com:greenhouse-org/bosh-agent.git
    private_key: {{GREENHOUSEORG_BOSH_AGENT_DEPLOY_KEY}}
- name: windows_app_lifecycle
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows_app_lifecycle
- name: windows_app_lifecycle_fork
  type: git
  source:
    branch: master
    uri: git@github.com:greenhouse-org/windows_app_lifecycle.git
    private_key: {{GREENHOUSEORG_WINDOWS_APP_LIFECYCLE_DEPLOY_KEY}}
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git

resource_types: []

jobs:
- name: build-tar
  serial: true
  plan:
  - aggregate:
    - get: bsdtar
      trigger: true
    - get: s3-bucket
  - task: build-tar
    config:
      platform: windows
      inputs:
      - name: bsdtar
      outputs:
      - name: tar-output
      run:
        path: powershell
        args:
        - bsdtar/install.ps1
  - put: s3-bucket
    params:
      file: tar-output/tar-*.exe

- name: windows-app-lifecycle-update-tar
  serial: true
  plan:
  - aggregate:
    - get: windows_app_lifecycle
    - get: windows_app_lifecycle_fork
    - get: s3-bucket
      trigger: true
      passed: [build-tar]
    - get: ci
  - task: update-tar
    file: ci/tasks/update-tar.yml
    params:
      TAR_PATHS: Builder/Resources/bsdtar.exe Builder.Tests/Resources/bsdtar.exe bin/bsdtar.exe
    input_mapping:
      repo: windows_app_lifecycle
  - task: commit
    file: ci/tasks/commit.yml
    params:
      MESSAGE: "Update bsdtar.exe"
    input_mapping:
      source_repo: updated_repo
      destination_repo: windows_app_lifecycle_fork
  - put: windows_app_lifecycle_fork
    params:
      repository: destination_repo_with_commit
  - task: create-tracker-task
    params:
      TOKEN: {{TRACKER_GITBOT_TOKEN}}
      PROJECT_ID: {{BOSH_WINDOWS_PROJECT_ID}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          curl -f -X POST -H "X-TrackerToken: $TOKEN" -H "Content-Type: application/json" -d '{"name":"New Build of Tar available!", "description": "A new build of tar.exe is available at https://github.com/greenhouse-org/windows_app_lifecycle. A PR should be made to windows_app_lifecycle official repo."}' "https://www.pivotaltracker.com/services/v5/projects/$PROJECT_ID/stories"

- name: bosh-agent-update-tar
  serial: true
  plan:
  - aggregate:
    - get: bosh-agent
    - get: bosh-agent-fork
    - get: s3-bucket
      trigger: true
      passed: [build-tar]
    - get: ci
  - task: update-tar
    file: ci/tasks/update-tar.yml
    params:
      TAR_PATHS: integration/windows/fixtures/tar.exe
    input_mapping:
      repo: bosh-agent
  - task: commit
    file: ci/tasks/commit.yml
    params:
      MESSAGE: "Update tar.exe"
    input_mapping:
      source_repo: updated_repo
      destination_repo: bosh-agent-fork
  - put: bosh-agent-fork
    params:
      repository: destination_repo_with_commit
  - task: create-tracker-task
    params:
      TOKEN: {{TRACKER_GITBOT_TOKEN}}
      PROJECT_ID: {{BOSH_WINDOWS_PROJECT_ID}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          curl -f -X POST -H "X-TrackerToken: $TOKEN" -H "Content-Type: application/json" -d '{"name":"New Build of Tar available!", "description": "A new build of tar.exe is available at https://github.com/greenhouse-org/bosh-agent. A PR should be made to the official bosh-agent repo."}' "https://www.pivotaltracker.com/services/v5/projects/$PROJECT_ID/stories"
