# To configure this pipeline: pipelines/configure.sh windows-docker-images
resources:
# dockerfiles

- name: ci-pivnet-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.pivnet ]

- name: ci-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.ci ]

- name: govc-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.govc ]

- name: ci-azcopy-dockerfile
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
    paths: [ docker/Dockerfile.azcopy ]

# docker build resources

- name: pivnet-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/pivnet
    username: ((docker.username))
    password: ((docker.password))

- name: ci-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci
    username: ((docker.username))
    password: ((docker.password))

- name: govc-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/govc
    username: ((docker.username))
    password: ((docker.password))

- name: ci-azcopy-image
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci-azcopy
    username: ((docker.username))
    password: ((docker.password))

- name: golang-release-image
  type: docker-image
  source:
    repository: bosh/golang-release
    username: ((docker.username))
    password: ((docker.password))

# dependency resources

jobs:
- name: build-and-push-pivnet
  serial: true
  plan:
  - get: ci-pivnet-dockerfile
    trigger: true
  - put: pivnet-image
    params:
      build: ci-pivnet-dockerfile/docker
      dockerfile: ci-pivnet-dockerfile/docker/Dockerfile.pivnet
      tag_as_latest: true

- name: build-and-push-ci
  serial: true
  plan:
  - get: ci-dockerfile
    trigger: true
  - get: golang-release-image
    trigger: true
  - put: ci-image
    params:
      build: ci-dockerfile/docker/
      dockerfile: ci-dockerfile/docker/Dockerfile.ci
      tag_as_latest: true

- name: build-and-push-govc
  serial: true
  plan:
    - get: govc-dockerfile
      trigger: true
    - put: govc-image
      params:
        build: govc-dockerfile/docker
        dockerfile: govc-dockerfile/docker/Dockerfile.govc
        tag_as_latest: true

- name: build-and-push-ci-azcopy
  serial: true
  plan:
    - get: ci-azcopy-dockerfile
      trigger: true
    - get: golang-release-image
      trigger: true
    - put: ci-azcopy-image
      params:
        build: ci-azcopy-dockerfile/docker
        dockerfile: ci-azcopy-dockerfile/docker/Dockerfile.azcopy
        tag_as_latest: true
