#!/usr/bin/env bash

set -ex

AWS_CREDS_FILE=~/.aws/credentials
mkdir ~/.aws

cat > ${AWS_CREDS_FILE} << EOF
[default]
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
EOF

cd stemcell-builder
bundle install
rake package:agent
rake package:psmodules
rake build:aws_ami

mv bosh-windows-stemcell/*.tgz ../bosh-windows-stemcell
mv bosh-windows-stemcell/*.sha ../sha
