---
platform: linux

inputs:
- name: bosh-windows-stemcell-builder-ci
- name: stembuild-untested-windows
- name: stembuild-untested-linux

outputs:
- name: final-stembuilds

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/set-stembuild-version/run.sh
