---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
- name: bosh-windows-stemcell-builder-ci
- name: stembuild-untested-windows
- name: stembuild-untested-linux

outputs:
- name: final-stembuilds

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/set-stembuild-version/run.sh
