#!/usr/bin/env bash
set -eu -o pipefail
set -x

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${PACKER_AWS_ACCESS_KEY}"
  set +x
  aws configure --profile creds_account set aws_secret_access_key "${PACKER_AWS_SECRET_KEY}"
  set -x
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  aws configure --profile resource_account set region "${AWS_REGION}"
  unset AWS_REGION
  export AWS_PROFILE=resource_account
else
  export AWS_ACCESS_KEY="${PACKER_AWS_ACCESS_KEY}"
  set +x
  export AWS_SECRET_KEY="${PACKER_AWS_SECRET_KEY}"
  set -x
fi

pushd lgpo-binary
    unzip LGPO.zip
popd

BOSH_AGENT_DIR="$(pwd)/${BOSH_AGENT_DIR}"
export BOSH_AGENT_DIR
pushd "${BOSH_AGENT_DIR}"
  BOSH_AGENT_VERSION=$(cat .resource/version)
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

pushd stemcell-builder
  pushd src/github.com/cloudfoundry/bosh-agent
    git fetch
    git checkout "v${BOSH_AGENT_VERSION}"
  popd

  bundle install --without test

  rake package:agent
  rake package:psmodules
  rake build:aws

  mv bosh-windows-stemcell/*.tgz ../bosh-windows-stemcell
  mv bosh-windows-stemcell/*.sha ../sha
  mv hotfixes.log ../hotfix-log/
popd
