#!/usr/bin/env bash

set -ex

export BOSH_AGENT_DIR="$(pwd)/$BOSH_AGENT_DIR"
pushd "${BOSH_AGENT_DIR}"
  CURRENT_VERSION=$(cat .resource/version)
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

pushd lgpo-binary
    unzip LGPO.zip
popd

if [ -n "${AWS_ROLE_ARN}" ]; then
  aws configure --profile creds_account set aws_access_key_id "${PACKER_AWS_ACCESS_KEY}"
  aws configure --profile creds_account set aws_secret_access_key "${PACKER_AWS_SECRET_KEY}"
  aws configure --profile resource_account set source_profile "creds_account"
  aws configure --profile resource_account set role_arn "${AWS_ROLE_ARN}"
  aws configure --profile resource_account set region "${AWS_REGION}"
  unset AWS_REGION
  export AWS_PROFILE=resource_account
else
  export AWS_ACCESS_KEY="${PACKER_AWS_ACCESS_KEY}"
  export AWS_SECRET_KEY="${PACKER_AWS_SECRET_KEY}"
fi

pushd stemcell-builder
  pushd src/github.com/cloudfoundry/bosh-agent
    git fetch
    git checkout "v$CURRENT_VERSION"
  popd
  bundle install --without test
  rake package:agent
  rake package:psmodules
  rake build:aws
popd

mv stemcell-builder/bosh-windows-stemcell/*.tgz bosh-windows-stemcell
mv stemcell-builder/bosh-windows-stemcell/*.sha sha

mv stemcell-builder/hotfixes.log hotfix-log/
