---
platform: linux

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: version
  - name: amis
  - name: default-stemcell
  - name: bosh-agent-release
  - name: bosh-psmodules-repo
  - name: blobstore-dav-cli
  - name: blobstore-s3-cli
  - name: blobstore-gcs-cli
  - name: windows-bsdtar
  - name: windows-winsw


outputs:
  - name: copied-regional-stemcells

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/copy-aws-stemcell/run

params:
  OS_VERSION:
  AWS_ACCESS_KEY:
  AWS_ROLE_ARN:
  AWS_SECRET_KEY:
  REGIONS:
  VERSION_DIR: ../version
  AMIS_DIR: ../amis
  DEFAULT_STEMCELL_DIR: ../default-stemcell
  BOSH_AGENT_DIR: bosh-agent-release
  BOSH_PSMODULES_DIR: bosh-psmodules-repo
