#!/usr/bin/env bash

source  ./ci/common-scripts/setup_bosh_proxy.sh

setup_bosh_proxy "$SSH_TUNNEL_USER" "$SSH_TUNNEL_IP" "$SSH_TUNNEL_PRIVATE_KEY"

set -ex

bosh upload-stemcell heavy_stemcell_dir/*.tgz -n --fix
