#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require 'digest'

def new_stemcell_name(old_stemcell_path, final_version)
  File.basename(old_stemcell_path).gsub(/\d+\.\d+\.\d+(-build\.\d+)?/, final_version)
end

Dir.chdir File.join(File.dirname(__FILE__), "..", "..")

stemcell = Dir.glob("bosh-windows-stemcell/*.tgz")
final_version = File.read("version/number").match(/\d+\.\d+/)[0]

printf $final_version > final-stemcell/version

stemcell_name = new_stemcell_name(stemcell[0], final_version)
FileUtils.mv stemcell[0], File.join("final-stemcell", stemcell_name)
