#!/usr/bin/env bash

set -eux

export GOPATH=$PWD/garden-runc-release
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH
go version

curl -k --silent --head --fail http://$GARDEN_ADDRESS:$GARDEN_PORT/ping

cd garden-runc-release
go install ./src/github.com/onsi/ginkgo/ginkgo

rm -rf src/code.cloudfoundry.org/garden-integration-tests
echo "Copying GATs fork..."
cp -r ../garden-integration-tests src/code.cloudfoundry.org/

cd src/code.cloudfoundry.org/garden-integration-tests
ginkgo -p -randomizeSuites -noisyPendings=false
