#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd lgpo-binary
  unzip LGPO.zip
popd

CONCOURSE_ROOT="$(pwd)"

BOSH_AGENT_DIR="${CONCOURSE_ROOT}/${BOSH_AGENT_DIR}"
export BOSH_AGENT_DIR

pushd stemcell-builder
  tasks/build-agent-zip/run.sh

  bundle install --without test

  rake package:psmodules
  rake build:gcp

  mv bosh-windows-stemcell/* ../bosh-windows-stemcell

  mv hotfixes.log ../hotfix-log/
popd
