#!/usr/bin/env bash
set -eu -o pipefail
set -x

pushd lgpo-binary
  unzip LGPO.zip
popd

BOSH_AGENT_DIR="$(pwd)/${BOSH_AGENT_DIR}"
export BOSH_AGENT_DIR
pushd "${BOSH_AGENT_DIR}"
  BOSH_AGENT_VERSION=$(cat .resource/version)
  mv bosh-agent-pipe*.exe pipe.exe
  mv bosh-agent*.exe bosh-agent.exe
popd

pushd stemcell-builder
  pushd src/github.com/cloudfoundry/bosh-agent
    git fetch
    git checkout "v${BOSH_AGENT_VERSION}"
  popd

  bundle install --without test

  rake package:agent
  rake package:psmodules
  rake build:gcp

  mv bosh-windows-stemcell/*.tgz ../bosh-windows-stemcell/

  mv hotfixes.log ../hotfix-log/
popd
