#!/bin/bash

set -eo pipefail

ACCOUNT_EMAIL=$(echo $ACCOUNT_JSON | jq -r .client_email)
PROJECT_ID=$(echo $ACCOUNT_JSON | jq -r .project_id)

gcloud auth activate-service-account --quiet $ACCOUNT_EMAIL --key-file <(echo $ACCOUNT_JSON)
gcloud config set project $PROJECT_ID

set -x

base_image_regex=""
image_family=""
if [ "$BASE_OS" == "windows2012R2" ]; then
  base_image_regex="windows-server-2012-r2-dc-v.*"
  image_family="windows-2012-r2"
elif [ "$BASE_OS" == "windows2016" ]; then
  base_image_regex="windows-server-2016-dc-core-v.*"
  image_family="windows-2016-core"
else
  echo "Define BASE_OS environment variable (e.g. windows2012R2,windows2016)" 1>&2
	exit 1
fi

image_id=$(gcloud compute images list --regexp ${base_image_regex} --format json | jq -r .[0].name)
version=$(cat version/number)

printf '{"base_image":"%s","image_family":"%s"}' "$image_id" "$image_family" > base-gcp-image/base-gcp-image-$BASE_OS-$version.json

