#!/usr/bin/env ruby

require 'fileutils'

script_path = File.join("garden-runc-release", "jobs", "garden-windows", "templates", "garden_ctl.ps1.erb" )
ctl_script = File.read(script_path, encoding: 'bom|utf-8')

modified_ctl_script = "netsh advfirewall firewall add rule name=\"Open Port 7777\" dir=in action=allow protocol=TCP localport=7777\n" +
                      ctl_script

File.write(script_path, modified_ctl_script)

FileUtils.cp_r(Dir["garden-runc-release/*"], "garden-runc-release-open-port")
