---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
- name: stembuild
outputs:
- name: stembuild-commit
run:
  path: bash
  args:
  - "-c"
  - "cd stembuild && git rev-parse HEAD > ../stembuild-commit/sha"
