#!/usr/bin/env bash

set -ex

chmod 0600 greenhouse-private/opsmanager/keypair/pcf-user.pem
ssh -M -S ctrl-socket -fnNT -o "StrictHostKeyChecking no" $OPSMANAGER_VM_USER@$OPSMANAGER_VM_IP -i greenhouse-private/opsmanager/keypair/pcf-user.pem -L 25555:$BOSH_DIRECTOR_IP:25555

bosh target localhost
DEPLOYMENT_NAME=$(bosh deployments | head -5 | tail -1 | cut -d " " -f 2)
bosh download manifest $DEPLOYMENT_NAME manifest.yml

ruby <<EOF
require "yaml"
yaml = YAML.load_file("./manifest.yml")
yaml['jobs'].detect {|x| x['name'] =~ /^uaa-partition-/ } ['properties']['uaa']['scim']['users'].each do |user|
	if  user =~ /^admin\|.*\|/
		user.gsub!(/^admin\|.*\|/, "admin\|#{ENV.fetch('CF_PASSWORD')}\|")
		break
	end
end

File.write("./$DEPLOYMENT_NAME", yaml.to_yaml)
EOF

bosh -n --color -d ./$DEPLOYMENT_NAME deploy
ssh -S ctrl-socket -O exit $OPSMANAGER_VM_USER@$OPSMANAGER_VM_IP
