#!/bin/bash
# vi: ft=sh

set -e -x -u

# echo "----- Copy private blobstore credentials into garden-windows-release"
cp greenhouse-private/garden-windows-bosh-release/private.yml release-develop/config/private.yml

FINAL_RELEASE_VERSION=$(cat version/number)
DEV_RELEASE_TARBALL=$(ls $PWD/bucket-develop/*.tgz)

pushd release-develop
  RELEASE_YML=$PWD/releases/garden-windows/garden-windows-${FINAL_RELEASE_VERSION}.yml
  RELEASE_TGZ=$PWD/releases/garden-windows/garden-windows-${FINAL_RELEASE_VERSION}.tgz

  # idempotently create tarball in case later parts of shipit fail
  if [ -e "${RELEASE_YML}" ]; then
    echo "----- Release already created; making tarball..."
    bosh -n create release --with-tarball ${RELEASE_YML}
  else
    echo "----- Set git identity"
    git config user.email "cf-netgarden-eng@pivotal.io"
    git config user.name "CI (Automated)"

    echo "----- Create final release"
    bosh -n finalize release $DEV_RELEASE_TARBALL --version $FINAL_RELEASE_VERSION

    # echo "----- Adding master cloned release as remote"
    # git remote add local-diego-release-master ../diego-release-master
    # git fetch local-diego-release-master
    # git merge --no-edit local-diego-release-master/master

    echo "----- Update master and develop branches on origin"
    git add -A
    git commit -m "Create final release ${FINAL_RELEASE_VERSION}"

    echo "----- DEBUG: show the commit we just created"
    git --no-pager show HEAD
  fi

  # make tarball easier to reach by upstream things
  mv $RELEASE_TGZ ../finalized-release/garden-windows-$FINAL_RELEASE_VERSION.tgz
popd

cp -a release-develop finalized-release/
