#!/bin/bash

set -ex

environment_path="${PWD}/greenhouse-private/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"
ADD_WINDOWS_TOOLS=${ADD_WINDOWS_TOOLS:-0}

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/cf/*.yml \
    ${stubs_path}/diego/property-overrides.yml \
    > ../generated-manifest/cf-deployment.yml
popd

pushd diego-release
  spiff merge \
    manifest-generation/misc-templates/windows-iaas-settings.yml \
    ${templates_path}/diego-windows/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    ../generated-manifest/cf-deployment.yml \
    > /tmp/iaas-settings.yml

  cp ../generated-manifest/cf-deployment.yml /tmp/cf.yml

  ./scripts/generate-windows-cell-deployment-manifest \
    -c /tmp/cf.yml \
    -i /tmp/iaas-settings.yml \
    -p ${stubs_path}/diego-windows/property-overrides.yml \
    -n ${stubs_path}/diego-windows/instance-count-overrides.yml \
    -v ${stubs_path}/diego-windows/release-versions.yml \
    > ../generated-manifest/diego-windows-deployment.yml
popd

if [[ $ADD_WINDOWS_TOOLS -eq 1 ]]; then
  ci/scripts/add_windows_tools.rb \
    generated-manifest/diego-windows-deployment.yml \
    generated-manifest/diego-windows-deployment.yml
fi
