#!/bin/sh

set -e

( cd garden-windows-release && git rev-parse HEAD ) > generated-release/commitish

version=$(cat garden-windows-bosh-release-final/version)
echo "Garden Windows v$version" > generated-release/name
echo "v$version" > generated-release/version
