#!/bin/bash

echo "If you see the following error don't worry everything is working, the images got deleted, but some did not need to be deleted:"
echo "'X of Y blobs not deleted due to Failed Precondition'"

az storage blob delete-batch \
  --auth-mode key \
  --account-key $AZURE_STORAGE_ACCESS_KEY \
  --account-name $AZURE_STORAGE_ACCOUNT \
  --source=images --pattern="*.vhd" \
  --if-unmodified-since=$(date -d "90 days ago" '+%Y-%m-%dT%H:%MZ')