#!/usr/bin/env bash

set -e

function add-pivnet-productfile () {
  stembuild="$1"

  echo "Adding $stembuild to Pivnet metadata"

  cat >> metadata <<EOF
  - file: pivnet-metadata/$stembuild
    upload_as: "Stembuild test2 for $OS_NAME"
EOF
}

cat > pivnet-metadata/metadata <<EOF
---
release:
  version: "stembuild-promote-test"
  release_type: Beta Release
  eula_slug: "pivotal_beta_eula"
  availability: Selected User Groups Only
  user_group_ids:
    - 152
  eccn: ""
  license_exception: ""
product_files:
EOF

release_version=$(cat pivnet-release/metadata.json | jq .Release.Version)
echo "ls ***"
ls pivnet-release

if [ "$(ls pivnet-release/stembuild*)" != "" ] && [[ $release_version == *"$(cat stembuild/version)"* ]]; then
    mv pivnet-release/stembuild* pivnet-metadata
fi

mv stembuild/stembuild* pivnet-metadata/stembuild-test2

#mv pivnet-metadata/stembuild* pivnet-metadata/stembuild-test2

cd pivnet-metadata
for s in $(ls stembuild*)
  do
    add-pivnet-productfile "$s"
done
cd ..

echo 'Release details:'
cat pivnet-metadata/metadata

echo 'stembuilds:'
ls pivnet-metadata/stembuild*
