#!/usr/bin/env bash

set -e

function add-pivnet-productfile () {
  stembuild="$1"

  echo "Adding $stembuild to Pivnet metadata"

  cat >> metadata <<EOF
  - file: pivnet-metadata/$stembuild
    upload_as: "Stembuild test for $OS_NAME"
EOF
}

stemcell=`ls stembuild/stembuild*`
stemcellname=stembuild4

cat > pivnet-metadata/metadata <<EOF
---
release:
  version: "stembuild-promote-test"
  release_type: Beta Release
  eula_slug: "pivotal_beta_eula"
  availability: Selected User Groups Only
  user_group_ids:
    - 152
  eccn: ""
  license_exception: ""
file_groups:
  - name: "sample-group"
    product_files:
    - file: pivnet-metadata/stembuild/$stemcell
      upload_as: "$stemcellname Stemcell for $OS_NAME"
EOF

release_version=$(cat pivnet-release/metadata.json | jq -r .Release.Version)
echo "ls ***"
ls pivnet-release

echo "stembuild-promote-test" > stembuild/version

if [ "$(ls pivnet-release/stembuild*)" != "" ] && [[ $release_version == *"$(cat stembuild/version)"* ]]; then
    mv pivnet-release/stembuild* pivnet-metadata
fi

mkdir pivnet-metadata/stembuild
mv -t pivnet-metadata/stembuild stembuild/stembuild*

#mv pivnet-metadata/stembuild* pivnet-metadata/stembuild-test2

#cd pivnet-metadata
#for s in $(ls stembuild*)
#  do
#    add-pivnet-productfile "$s"
#done
#cd ..

echo 'Release details:'
cat pivnet-metadata/metadata

echo 'stembuilds:'
ls pivnet-metadata/stembuild*

cat pivnet-release/metadata.json
echo
echo $release_version
cat stembuild/version
