#!/usr/bin/env bash

set -eux

NEW_VERSION=$(cat version/version)
CREATE_BIN_SHA_WINDOWS=$(cat create-windows-sha/create-*-windows-amd64.exe.sha256)
CREATE_BIN_SHA_LINUX=$(cat create-linux-sha/create-*-linux-amd64.sha256)

pushd windows2016fs-release
	echo -n $NEW_VERSION > VERSION
	echo -n $CREATE_BIN_SHA_WINDOWS > CREATE_BIN_SHA_WINDOWS
	echo -n $CREATE_BIN_SHA_LINUX > CREATE_BIN_SHA_LINUX

	git config --global user.email "pivotal-netgarden-eng@pivotal.io"
	git config --global user.name "Greenhouse CI"
	git add VERSION CREATE_BIN_SHA_WINDOWS CREATE_BIN_SHA_LINUX

	commit_message="Bumped version to $NEW_VERSION"
	git commit -m "$(echo -e $commit_message)"
popd

cp -r windows2016fs-release/. windows2016fs-release-updated-version

