#!/usr/bin/env bash

set -e

stemcell_filename=$(cd final-stemcell && ls *.tgz)
echo "stemcell_filename: ${stemcell_filename}"

checksum=$(shasum -a 1 final-stemcell/*.tgz | awk '{print $1}')
echo "checksum: ${checksum}"

curl -X POST \
    --fail \
    -d "sha1=${checksum}" \
    -H "Authorization: bearer ${BOSHIO_TOKEN}" \
    "https://bosh.io/checksums/${stemcell_filename}"
