#!/usr/bin/env bash

set -ex

version=`cat version/number`
uri_filename="bosh-stemcell-*-azure-vhd-uri.txt"
image_url=`cat azure-base-vhd-uri/$uri_filename`

def format_version {

}
vm_version=$(format_version)
tenant_id=a288e0e4-4e8b-4fed-85ff-05f3ce84a057
client_id=2a47ea93-2add-4d34-a6e1-0bc3cfd2a941
client_secret='N0MjOjNMXTJ7dW5HOFJ0ODFBZEFqZ1F6bjJwNmM6cCk='
grant_type=client_credentials
resource=https://cloudpartner.azure.com
token=$(curl -X POST "https://login.microsoftonline.com/$tenant_id/oauth2/token" -F "client_id=$client_id" -F "client_secret=$client_secret" -F "grant_type=$grant_type" -F "resource=$resource" 2>/dev/null | jq -r .access_token)

publisher_id=pivotal
offer_id=bosh-windows-server-2019
offer_config=$(curl -X GET "https://cloudpartner.azure.com/api/publishers/$publisher_id/offers/$offer_id?api-version=2017-10-31" -H "Authorization: Bearer $token" -H "Content-Type: application/json")

vm_image_path=".definition.plans[] | select(.planId == \"$SKU\") | .[\"microsoft-azure-virtualmachines.vmImages\"]"
new_vm_object="{\"$vm_version\": {\"osVhdUrl\":\"$image_url\", \"lunVhdDetails\": []}"
add_image_to_plan='('"$vm_image_path"') |= . + '"$new_vm_object"'}'

echo $offer_config | jq "$add_image_to_plan"