#!/usr/bin/env bash

set -eu

export GOPATH=$(cd "$GOPATH" && pwd)
export PATH="$PATH:$GOPATH/bin"

go get github.com/onsi/ginkgo/ginkgo

pushd repo
  ginkgo -p -r -race -keepGoing -randomizeSuites -skipPackage "$IGNORE_PACKAGES" "$TEST_PATH"
popd
