---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
  - name: bosh-windows-stemcell-builder-ci
  - name: stemcell-builder
  - name: blobstore-dav-cli
  - name: blobstore-s3-cli
  - name: blobstore-gcs-cli
  - name: windows-bsdtar
  - name: windows-winsw

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/test-stemcell-builder/run
