---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
- name: stemcell-builder
- name: bosh-agent-release
- name: ci
- name: blobstore-dav-cli
- name: blobstore-s3-cli
- name: windows-bsdtar

outputs:
- name: bosh-agent
run:
  path: ci/tasks/build-agent-zip/run.sh

params:
  BOSH_AGENT_DIR: bosh-agent-release