#!/usr/bin/env bash

set +x
source ../../common/setup_bosh_proxy.sh

setup_bosh_proxy ${SSH_TUNNEL_USER} ${SSH_TUNNEL_IP} ${SSH_TUNNEL_PRIVATE_KEY}

set -ex

export STEMCELL_PATH=$(readlink -f ${STEMCELL_PATH})

cd stemcell-builder
bundle install --without test
rake package:bwats
rake run:bwats[${IAAS}]
