#!/usr/bin/env ruby

require 'fileutils'

require_relative '../../../stemcell-builder/lib/exec_command'

Dir.chdir "stemcell-builder" do
  exec_command("bundle install --without test")
  exec_command("rake package:agent")
  exec_command("rake package:psmodules")
  exec_command("rake build:vsphere")
end
