#!/usr/bin/env ruby
require 'json'

dirs = %w(stemcell-builder
          stemcell-builder/src/github.com/cloudfoundry/bosh-agent
          stemcell-builder/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests)

final_version = File.read("version/version")

if final_version.match('1200')
  filename = "stemcell-#{final_version}.json"
elsif final_version.match('1709')
  filename = "2016-stemcell-#{final_version}.json"
elsif final_version.match('1803')
  filename = "1803-stemcell-#{final_version}.json"
elsif final_version.match('2019')
  filename = "2019-stemcell-#{final_version}.json"
else
  throw "invalid stemcell version: #{final_version}"
end

shas = dirs.inject({}) do |acc, dir|
  acc[dir.split('/').last] = `cd #{dir}; git rev-parse HEAD`.chomp
  acc
end

File.write(
  File.join('stemcell-info', filename),
  JSON.dump(shas)
)
