---
platform: linux
image_resource: { type: docker-image, source: {repository: pivotalgreenhouse/govc } }

inputs:
  - name: bosh-windows-stemcell-builder-ci

run:
  path: bosh-windows-stemcell-builder-ci/ci/tasks/update-snapshot/run.sh

params:
  GOVC_URL:
  DATACENTER:
  VM_TO_SNAPSHOT:
  SNAPSHOT_NAME:
